### ISSUE TITLE
Request with http instead of SMTP

### ISSUE THREAD

**Issue by LiuQhahah** [resendlabs/resend-go#14]
From the code  https://github.com/resendlabs/resend-go/blob/main/emails.go#L150

`	req, err := s.client.NewRequest(http.MethodPost, path, convertedParams)
`
I want to know the reason that sending email with HTTP, instead of SMTP.
Thanks

**Comment by drish** [comment]
Hey @LiuQhahah the Resend API is primarily an HTTP based API. We have just recently added support for SMTP, however the core of the functionality of the SDKs are based on their HTTP endpoints, sending through SMTP depends is basically a matter of configuring your SMTP client of choice to use Resend credentials.

Hope that answers your question !
