### ISSUE TITLE
unable to install v2.1.0

### ISSUE THREAD

**Issue by tonygits** [resendlabs/resend-go#19]
require github.com/resendlabs/resend-go: version "v2.1.0" invalid: should be v0 or v1, not v2

**Comment by drish** [comment]
hey @tonygits thanks for opening this ticket. Yeah we're aware of that issue, it should be resolved soon. Will update this ticket when its resolved.

**Comment by drish** [comment]
@tonygits you should be able to install the latest SDK with `go get github.com/resendlabs/resend-go/v2` now, let me know if you still run into any issues.

**Comment by firminochangani** [comment]
@drish It works like a charm 🤝

![Screenshot 2023-11-30 at 00 02 53](https://github.com/resendlabs/resend-go/assets/1679333/84d60af3-2530-40e8-a659-ede30f0c2743)

**Comment by drish** [comment]
awesome, closing this ticket, feel free open a new one if you need help with anything.
