### ISSUE TITLE
Update to go 1.23 (or 1.22)

### ISSUE THREAD

**Issue by matoszz** [resendlabs/resend-go#39]
Hi, new resend customer here - I'm working on implementing Resend into our go backend codebase and it would be great to see more ongoing support / activity for this SDK, especially keeping up to date with go versions. If PR's are welcome I'd be happy to bump the version in a PR. Thanks!

**Comment by drish** [comment]
hey @matoszz, thanks for opening this issue, I was actually thinking about adding support for newer go versions recently, and in fact I have just opened a [CI PR that will enable us to more easily point to newer go versions](https://github.com/resend/resend-go/pull/40). And yes, PRs are definitely welcome, once we have that CI support merged, we can push a PR pointing to a newer version.

**Comment by matoszz** [comment]
That's awesome, happy to hear it and thanks for the quick response @drish - let me know how I can help!

**Comment by matoszz** [comment]
not sure if this examples repo is still used / relevant, but I went ahead and uplifted it: https://github.com/resend/resend-go-example/pull/5

**Comment by matoszz** [comment]
@drish one thing to note about your PR updating the go version matrix testing... 1.23 is the current and golang formally supports only 1 major down so ideally your matrix would be testing 1.23, 1.22 (and possibly 1.21); go 1.17 was deprecated in August 2, 2022 for example.

**Comment by drish** [comment]
> @drish one thing to note about your PR updating the go version matrix testing... 1.23 is the current and golang formally supports only 1 major down so ideally your matrix would be testing 1.23, 1.22 (and possibly 1.21); go 1.17 was deprecated in August 2, 2022 for example.

yep good call, ill update that pr to support the latest versions

**Comment by drish** [comment]
@matoszz I just merged: https://github.com/resend/resend-go/pull/40 and released https://github.com/resend/resend-go/releases/tag/v2.12.0. Lmk if that works well for you
